export const DATABASE_SET_COLLECTIONS = "DATABASE_SET_COLLECTIONS";
export const DATABASE_MAKE_READY = "DATABASE_MAKE_READY";
export const DATABASE_MAKE_UNREADY = "DATABASE_MAKE_UNREADY";
export const DATABASE_MAKE_SORTED = "DATABASE_MAKE_SORTED";
export const DATABASE_MAKE_UNSORTED = "DATABASE_MAKE_UNSORTED";
export const DATABASE_SORT_COLLECTIONS = "DATABASE_SORT_COLLECTIONS";
